apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mongodb-helm-chart.fullname" . }}-mongo-express
  labels:
    app: mongo-express
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: {{ include "mongodb-helm-chart.fullname" . }}-secret
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom: 
            secretKeyRef:
              name: {{ include "mongodb-helm-chart.fullname" . }}-secret
              key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom: 
            configMapKeyRef:
              name: {{ include "mongodb-helm-chart.fullname" . }}-configmap
              key: database_url
        resources:
          limits:
            memory: {{ .Values.limits.memory }}
            cpu: "{{ .Values.limits.cpu }}"
          requests:
            memory: {{ .Values.requests.memory }}
            cpu: "{{ .Values.requests.cpu }}"
