apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mongodb-helm-chart.fullname" . }}-mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ include "mongodb-helm-chart.fullname" . }}-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: {{ include "mongodb-helm-chart.fullname" . }}-secret
              key: mongo-root-password
